### ISSUE TITLE
Configure the build system for the automatic build of the golang-part.

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/SimpleMdns#12]
probably need to add makefile, which will auto build gradle from artifacts from current p2chat repo

**Comment by ChronosX88** [comment]
You also need to add a submodule for the native part.

**Comment by ChronosX88** [comment]
I don't know, but it may useful: https://developer.android.com/studio/projects/gradle-external-native-builds

**Comment by ChronosX88** [comment]
And... We can use gradle for Go builds, I know gradle plugin for this.
